### ISSUE TITLE
[Bug]: php artisan native:serve broken pipe

### ISSUE THREAD

**Issue by oliver-tran** [NativePHP/laravel#176]
### What happened?

Hi, first of all, thanks for this great initiative!

I tried installing everything, installed a few missing libraries but got the following error message when trying to run the server:

```
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted

[87:0100/000000.756994:ERROR:zygote_linux.cc(661)] write: Broken pipe (32)
```

Installed using Docker, with the following configuration files:

**docker-compose.yml**
```
version: '3'

services:
 php:
  container_name: nativephp
  image: nativephp
  build:
   context: ./docker/php
  volumes:
   - .:/home/app
  ports:
   - "9000:90"
  working_dir: /home/app
  networks:
   network:
    ipv4_address: 172.15.0.2

networks:
 network:
  driver: bridge
  ipam:
   driver: default
   config:
    - subnet: 172.15.0.0/16
      gateway: 172.15.0.1
```

**Dockerfile**
```
FROM php:8.1.22-fpm

WORKDIR /home/app

# OPERATIVE SYSTEM
RUN apt-get update
RUN apt-get install -y \
    libfreetype-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libgconf-2-4 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libgdk-pixbuf2.0-0 \
    libgtk-3-0 \
    libgbm-dev \
    libnss3-dev \
    libxss-dev \
    libasound2

# USER
RUN useradd app --create-home --password "password" --shell /bin/bash
RUN usermod -aG sudo username

# PHP
RUN docker-php-ext-configure gd --with-freetype --with-jpeg
RUN docker-php-ext-install -j$(nproc) gd

# COMPOSER
RUN php -r "copy('https://getcomposer.org/installer', '/home/app/composer-setup.php');"
RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer
RUN chmod +x /usr/local/bin/composer
RUN rm /home/app/composer-setup.php

# NPM
RUN apt-get install -y nodejs npm

# CLEAN
RUN apt-get autoclean
```

### How to reproduce the bug

**CLI command sequence I ran**
```
su - app
cd /home
composer create-project laravel/laravel tmp
cd /home/app
mv tmp/* .
mv tmp/.* .
rm -r tmp
composer require nativephp/electron
php artisan native:install
logout
chown root: /home/app/vendor/nativephp/electron/resources/js/node_modules/electron/dist/chrome-sandbox
chmod 4755 /home/app/vendor/nativephp/electron/resources/js/node_modules/electron/dist/chrome-sandbox
su - app
php artisan native:serve
```

### Package Version

0.4.0

### PHP Version

8.1.22

### Laravel Version

10.18.0

### Node Version

9.2.0

### Which operating systems does with happen with?

Debian 12 dockered on Windows 10
