### ISSUE TITLE
[Bug]: Can't build package in CI environment

### ISSUE THREAD

**Issue by danjohnson95** [NativePHP/laravel#179]
### What happened?

I'm attempting to build a NativePHP application in GitHub Actions, but I'm seeing an error when the `php artisan native:build` command is run.

The stack trace I'm seeing is available here:
https://github.com/danjohnson95/larajobs-desktop/actions/runs/5861056482/job/15890428280?pr=3#step:5:67

Specifically, the error is:

```
Symfony\Component\Process\Exception\RuntimeException 

  TTY mode requires /dev/tty to be read/writable.

  at vendor/symfony/process/Process.php:1023
    1019▕             throw new RuntimeException('TTY mode is not supported on Windows platform.');
    1020▕         }
    1021▕ 
    1022▕         if ($tty && !self::isTtySupported()) {
  ➜ 1023▕             throw new RuntimeException('TTY mode requires /dev/tty to be read/writable.');
    1024▕         }
    1025▕ 
    1026▕         $this->tty = $tty;
    1027▕

      +15 vendor frames 

  16  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

Error: Process completed with exit code 1.
```

I expected the build command to be runnable in a CI environment, and to see output indicating that the application was successfully compiled for the macOS platform.

### How to reproduce the bug

I've created a GitHub Actions workflow file running on the `macos-latest` runner.

The contents of the workflow file are:

```yaml
name: Build

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Run build
        run: php artisan native:build
```

I've also [added GitHub Action Secrets for codesigning the application](https://danjohnson.xyz/en/blog/signing-your-native-php-application).

### Package Version

0.4.0

### PHP Version

8.1.0

### Laravel Version

10.10

### Node Version

18.16.1

### Which operating systems does with happen with?

macOS
